apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz  # healthcheck 내역 경로
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3  #app이 뜨는데 3초가 걸리는 등 pod가 open되는데 필요한 min time
      periodSeconds: 3  # check 시작 시 앞으로의 check 간격