# 조건
# MYSQL_USER: user1
# MYSQL_PASSWORD: pw1234
# MYSQL_ROOT_PASSWORD: rootpw9876
# MYSQL_DATABASE: mydb

apiVersion: v1
kind: Secret
metadata:
  name: secret-exe
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_USER: dXNlcjEK # echo user1 | base64
  MYSQL_PASSWORD: cHcxMjM0Cg== # echo pw1234 | base64
  MYSQL_ROOT_PASSWORD: cm9vdHB3OTg3Ngo= # echo rootpw9876 | base64
  MYSQL_DATABASE: bXlkYgo= # echo mydb | base64
