# 환경변수로 주입

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: nginx
      env:
        # container 안에 env 이름
        - name: USERNAME
          valueFrom:
            secretKeyRef:
            # secret 이름
              name: my-secret2
            # secret key
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password