# kubetemp/config-dir/custom-nginx-config.conf
server {
    listen                8080;
    server_name        www.acron.com;

    gzip on;
    gzip_types text/plain application/xml;
    location / {
        root    /usr/share/nginx/html;
        index    index.html index.htm;
    }
}

#kubectl create configmap nginx-config --from-file=config-dir
# configmap 만들어라        이름           이 dir에 있는 파일 다 넣어라