# fortune-svc.yml
# LB svc
apiVersion: v1
kind: Service
metadata:
  name: fortune-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: fortune
  ports:
    - port: 80
      targetPort: 80
  # local k8s는 LB를 생성할 수 없다. (Ingress/LB ctrller가 없어서)
  # local에서 LB를 구성할 경우, 주석과 같이 외부의 IP를 적어서 LB로 기능하도록 한다.
  type: LoadBalancer
  # externalIPs:
  # - 192.168.0.2