# Pod 이름: my-redis
# 컨테이너 이름: redis
# 컨테이너 이미지: redis:7.2
# 컨테이너가 6379번 포트로 서비스

apiVersion: v1
kind: Pod
metadata:
  name: my-redis
spec:
  containers:
  - name: redis
    image: redis:7.2
    ports:
    - containerPort: 6379
