# replication controller 실습
# pod는 죽이면 죽는다
# replication이 다시 살릴 뿐...

apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp-rc
spec:
  # replica 갯수
  replicas: 3
  # label selector
  selector:
  # 감시대상, goapp
    app: goapp
  template:
    metadata:
      name: goapp-pod
      labels:
        tier: forntend
        # label이 app: goapp인 애를 감시
        app: goapp
        env: prod
        priority:  high
    spec:
      containers:
      - name: goapp-container
        image: dangtong/goapp
        ports:
        - containerPort: 8080

# EX: label을 overwrite하게 되면 1개가 감시 대상에서 빠져서, RC가 1개를 더 생성하게 된다.
# kubectl delete rc goapp-rc --cascade=orphan >> RC만 삭제하고, pod는 remain
# pod 삭제는 kubectl delete po <podId> 일일히